### ISSUE TITLE
Concatenate does not return correct result on GPU; works fine on CPU

### ISSUE THREAD

**Issue by fchollet** [Theano/Theano#2945]
There is a critical bug with concatenation on GPU...

The following operation:
```python
import theano.tensor as T
T.concatenate(tensors, axis=-1)
```
works fine on CPU (returns a tensor that is the concatenation of the inputs over the last dimension), but on GPU it returns the *last* tensor in the input list.

Here is the minimum code to reproduce:
```python
import theano
import theano.tensor as T 
import numpy as np

a = T.matrix()
b = T.matrix()

c = T.concatenate([a, b], axis=-1)

f = theano.function([a, b], c, allow_input_downcast=True)

a_np = np.random.random((10, 20))
b_np = np.random.random((10, 20))

out = f(a_np, b_np)
print out.shape # expect (10, 40)
```

This code will output `(10, 40)` on CPU (correct) and `(10, 20)` on GPU (wrong). The tensor being returned in this is actually `b_np`.

**Comment by bouthilx** [comment]
@fchollet This bug should have been fixed a week ago. Do you have an up-to-date dev-version of theano?

**Comment by alvarouc** [comment]
I upgraded from pip but the problem persists. Is this fix on pip yet?

**Comment by fchollet** [comment]
I reinstalled the latest version from pip a few hours ago. Let me pull master and check.

**Comment by bouthilx** [comment]
I ran your code and I get correct shape (10, 40). Try updating from github repo

```
pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
```
(comes from [here](http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions))

**Comment by fchollet** [comment]
Just reinstalled from master and it works now. Thanks for the help!

**Comment by nouiz** [comment]
Just to document, the problem is with the negative axis. The last release
do not support it. The dev version yes. If you use positive axis, the last
release support it.

**Comment by fchollet** [comment]
It's cool that the dev version supports this. It seems logical, in order be consistent with the Numpy API.

The previous issue was no so much the lack of support for negative axis concatenation, but rather: 
1) inconsistent behavior on CPU/GPU
2) returning an incorrect value instead of throwing an exception
