### ISSUE TITLE
No such file or directory: 

### ISSUE THREAD

**Issue by cancan101** [Theano/Theano#3115]
I have the following set:

```
optimizer_including = cudnn
assert_no_cpu_op=warn
```

and the cache directory is on an nfs mount.

I am getting the following error all though most of the time (not all of the time), the process continues. Further cuDNN should be available on the box(es) (error goes away when the cache dir path is no longer on NFS):

```
ERROR (theano.gof.opt): SeqOptimizer apply <theano.sandbox.cuda.dnn.NoCuDNNRaise object at 0x2b6ff3f58550>
ERROR (theano.gof.opt): Traceback:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "/home/ubuntu/git/Theano/theano/gof/opt.py", line 193, in apply
    sub_prof = optimizer.optimize(fgraph)
  File "/home/ubuntu/git/Theano/theano/gof/opt.py", line 78, in optimize
    ret = self.apply(fgraph, *args, **kwargs)
  File "/home/ubuntu/git/Theano/theano/sandbox/cuda/dnn.py", line 1714, in apply
    if not dnn_available():
  File "/home/ubuntu/git/Theano/theano/sandbox/cuda/dnn.py", line 75, in dnn_available
    v = version()
  File "/home/ubuntu/git/Theano/theano/sandbox/cuda/dnn.py", line 207, in version
    profile=False)
  File "/home/ubuntu/git/Theano/theano/compile/function.py", line 310, in function
    output_keys=output_keys)
  File "/home/ubuntu/git/Theano/theano/compile/pfunc.py", line 523, in pfunc
    output_keys=output_keys)
  File "/home/ubuntu/git/Theano/theano/compile/function_module.py", line 1526, in orig_function
    defaults)
  File "/home/ubuntu/git/Theano/theano/compile/function_module.py", line 1390, in create
    input_storage=input_storage_lists)
  File "/home/ubuntu/git/Theano/theano/gof/link.py", line 606, in make_thunk
    output_storage=output_storage)[:3]
  File "/home/ubuntu/git/Theano/theano/gof/vm.py", line 1025, in make_all
    no_recycling))
  File "/home/ubuntu/git/Theano/theano/sandbox/cuda/__init__.py", line 260, in make_thunk
    compute_map, no_recycling)
  File "/home/ubuntu/git/Theano/theano/gof/op.py", line 805, in make_thunk
    no_recycling)
  File "/home/ubuntu/git/Theano/theano/gof/op.py", line 732, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/ubuntu/git/Theano/theano/gof/cc.py", line 1068, in make_thunk
    keep_lock=keep_lock)
  File "/home/ubuntu/git/Theano/theano/gof/cc.py", line 1010, in __compile__
    keep_lock=keep_lock)
  File "/home/ubuntu/git/Theano/theano/gof/cc.py", line 1436, in cthunk_factory
    module = get_module_cache().module_from_key(
  File "/home/ubuntu/git/Theano/theano/gof/cc.py", line 81, in get_module_cache
    return cmodule.get_module_cache(config.compiledir, init_args=init_args)
  File "/home/ubuntu/git/Theano/theano/gof/cmodule.py", line 1416, in get_module_cache
    _module_cache = ModuleCache(dirname, **init_args)
  File "/home/ubuntu/git/Theano/theano/gof/cmodule.py", line 616, in __init__
    self.refresh()
  File "/home/ubuntu/git/Theano/theano/gof/cmodule.py", line 692, in refresh
    files = os.listdir(root)
OSError: [Errno 2] No such file or directory: '/home/ubuntu/.theano/compiledir_Linux-3.13--generic-x86_64-with-Ubuntu-14.04-trusty-x86_64-2.7.6-64/tmpgSidfq'
```

**Comment by nouiz** [comment]
Do you have many process running at the same time?

**Comment by cancan101** [comment]
Yes.

**Comment by nouiz** [comment]
I recently found a case that could happen with concurrent multiple process.
I tried it in this PR:

https://github.com/Theano/Theano/pull/3135

Can you try it to see if it fix it for you?

**Comment by nouiz** [comment]
Closing as the potential fix was merged.

**Comment by imk1** [comment]
I am still having this same problem, and I am using Theano 1.0.4, where the fix was implemented.
