### ISSUE TITLE
Failed to compile cuda_ndarray.cu on Windows 8.1

### ISSUE THREAD

**Issue by sergeyf** [Theano/Theano#3211]
Howdy, 

First let me say that I appreciate the work on this great library!

I had Theano working fine on my GPU, but wanted to update to the bleeding edge release. After uninstalling the pip version (0.7), I cloned the repository and then did `python setup.py develop`

Now Theano only imports without error when `device = cpu`. 

When trying `device = gpu`, I get the following error:

```
c:\users\s\documents\github\theano\theano\sandbox\cuda\cnmem.h(256): warning: __declspec attributes ignored

c:\users\s\documents\github\theano\theano\sandbox\cuda\cnmem.cpp(238): error: argument of type "const CRITICAL_SECTION *" is incompatible with parameter of type "LPCRITICAL_SECTION"

c:\users\s\documents\github\theano\theano\sandbox\cuda\cnmem.cpp(249): error: argument of type "const CRITICAL_SECTION *" is incompatible with parameter of type "LPCRITICAL_SECTION"

c:\users\s\documents\github\theano\theano\sandbox\cuda\cnmem.cpp(886): warning: variable "prev" was set but never used

c:\users\s\documents\github\theano\theano\sandbox\cuda\cnmem.cpp(910): warning: variable "result" was set but never used

mod.cu(800): warning: conversion from pointer to smaller integer

mod.cu(938): warning: pointless comparison of unsigned integer with zero

2 errors detected in the compilation of "C:/Users/S/AppData/Local/Temp/tmpxft_00002388_00000000-10_mod.cpp1.ii".
ERROR (theano.sandbox.cuda): Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 --compiler-bindir D:\\VS12\\VC\\bin\\amd64 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=4a12b69d331bcceb7766fff573cc0410,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -Ic:\\users\\s\\documents\\github\\theano\\theano\\sandbox\\cuda -IC:\\Anaconda\\lib\\site-packages\\numpy\\core\\include -IC:\\Anaconda\\include -Ic:\\users\\s\\documents\\github\\theano\\theano\\gof -o C:\\Users\\S\\AppData\\Local\\Theano\\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.9-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -LC:\\Anaconda\\libs -LC:\\Anaconda -lpython27 -lcublas -lcudart')
ERROR:theano.sandbox.cuda:Failed to compile cuda_ndarray.cu: ('nvcc return status', 2, 'for cmd', 'nvcc -shared -O3 --compiler-bindir D:\\VS12\\VC\\bin\\amd64 -Xlinker /DEBUG -D HAVE_ROUND -m64 -Xcompiler -DCUDA_NDARRAY_CUH=4a12b69d331bcceb7766fff573cc0410,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD -Ic:\\users\\s\\documents\\github\\theano\\theano\\sandbox\\cuda -IC:\\Anaconda\\lib\\site-packages\\numpy\\core\\include -IC:\\Anaconda\\include -Ic:\\users\\s\\documents\\github\\theano\\theano\\gof -o C:\\Users\\S\\AppData\\Local\\Theano\\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.9-64\\cuda_ndarray\\cuda_ndarray.pyd mod.cu -LC:\\Anaconda\\libs -LC:\\Anaconda -lpython27 -lcublas -lcudart')
mod.cu

['nvcc', '-shared', '-O3', '--compiler-bindir', 'D:\\VS12\\VC\\bin\\amd64', '-Xlinker', '/DEBUG', '-D HAVE_ROUND', '-m64', '-Xcompiler', '-DCUDA_NDARRAY_CUH=4a12b69d331bcceb7766fff573cc0410,-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION,/Zi,/MD', '-Ic:\\users\\s\\documents\\github\\theano\\theano\\sandbox\\cuda', '-IC:\\Anaconda\\lib\\site-packages\\numpy\\core\\include', '-IC:\\Anaconda\\include', '-Ic:\\users\\s\\documents\\github\\theano\\theano\\gof', '-o', 'C:\\Users\\S\\AppData\\Local\\Theano\\compiledir_Windows-8-6.2.9200-Intel64_Family_6_Model_60_Stepping_3_GenuineIntel-2.7.9-64\\cuda_ndarray\\cuda_ndarray.pyd', 'mod.cu', '-LC:\\Anaconda\\libs', '-LC:\\Anaconda', '-lpython27', '-lcublas', '-lcudart']
Traceback (most recent call last):

  File "<ipython-input-1-3397704bd624>", line 1, in <module>
    import theano

  File "c:\users\s\documents\github\theano\theano\__init__.py", line 103, in <module>
    import theano.sandbox.cuda

  File "c:\users\s\documents\github\theano\theano\sandbox\cuda\__init__.py", line 518, in <module>
    use(device=config.device, force=config.force_device, test_driver=False)

  File "c:\users\s\documents\github\theano\theano\sandbox\cuda\__init__.py", line 359, in use
    device, cuda_initialization_error_message))

EnvironmentError: You forced the use of gpu device gpu, but CUDA initialization failed with error:
cuda unavilable```

**Comment by nouiz** [comment]
I had a PR to fix this Friday and it got merged just now: gh-3204.

So just update Theano and it should work now.

**Comment by sergeyf** [comment]
Great, thank you!

**Comment by flyfj** [comment]
Is it working? I'm using the latest release of Theano 0.7, I still have this issue.
