### ISSUE TITLE
exception_verbosity=high flag raises TypeError on python 3

### ISSUE THREAD

**Issue by Asagen** [Theano/Theano#3708]
Running the interpreting error messages example at: http://deeplearning.net/software/theano/tutorial/debug_faq.html with exception_verbosity=high produces the error:

    ValueError: Input dimension mis-match. (input[0].shape[0] = 2, input[1].shape[0]    = 3)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "faulty_scrip.py", line 10, in <module>
        f(np.ones((2,)), np.ones((3,)))
      File "/home/user/python_environments/asagen/lib/python3.5/site-    packages/theano/compile/function_module.py", line 867, in __call__
        storage_map=getattr(self.fn, 'storage_map', None))
      File "/home/user/python_environments/asagen/lib/python3.5/site-   packages/theano/gof/link.py", line 279, in raise_with_op
        storage_map_list.sort(key=itemgetter(3), reverse=True)
    TypeError: unorderable types: int() > NoneType()

I believe this to be a python3 compatibility issue since int can be compared to None in python2 but not python3 (also, it works for me when I use python2.)

**Comment by nouiz** [comment]
I think this was fixed in Theano development version:

http://deeplearning.net/software/theano/install.html#bleeding-edge-install-instructions

Can you confirm that you use Theano 0.7, the last release?

**Comment by Asagen** [comment]
Just reinstalled theano with `pip install --upgrade git+git://github.com/Theano/Theano.git` in a new virtual environment with python 3.4.1, and on a different machine.  I still get the same error.

**Comment by Sentient07** [comment]
@nouiz  I can reproduce this error with Theano 0.7.0 and python 3.4

**Comment by nouiz** [comment]
We won't update Theano 0.7 again. DO you reproduce it with Theano
development version? If not, then the problem is fixed in master.
Otherwise, a fix is still needed.

**Comment by Sentient07** [comment]
@nouiz will check that again and get back

**Comment by Sentient07** [comment]
@nouiz I'm not getting this error with the dev version. so i think no issues :+1:
