### ISSUE TITLE
`test_nvidia_driver1` fails with recent Theano dev version

### ISSUE THREAD

**Issue by tboquet** [Theano/Theano#4495]
I just pull the new version of a [docker container](https://hub.docker.com/r/tboquet/anacuthe7hc4/~/dockerfile/) with a recent dev version of Theano and when the cache is empty, I have an error.
I updated my nvidia drivers recently (v361.42) and this is my Theano version:

```python
short_version = '0.9.0dev1'
version = '0.9.0dev1'
git_revision = '256cc8ddead946e958449f5f773109126b94de93'
```

```python
Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 4007)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python2.7/site-packages/theano/__init__.py", line 112, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "/opt/conda/lib/python2.7/site-packages/theano/sandbox/cuda/tests/test_driver.py", line 40, in test_nvidia_driver1
    if not numpy.allclose(f(), a.sum()):
  File "/opt/conda/lib/python2.7/site-packages/theano/compile/function_module.py", line 908, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/opt/conda/lib/python2.7/site-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python2.7/site-packages/theano/compile/function_module.py", line 895, in __call__
    self.fn() if output_subset is None else\
TypeError: Argument not a CudaNdarray
Apply node that caused the error: GpuCAReduce{add}{1}(<CudaNdarrayType(float32, vector)>)
Toposort index: 0
Inputs types: [CudaNdarrayType(float32, vector)]
Inputs shapes: [(10000,)]
Inputs strides: [(1,)]
Inputs values: ['not shown']
Outputs clients: [[HostFromGpu(GpuCAReduce{add}{1}.0)]]
```

If I reinstall the 0.8.2 release I can import theano and run [a simple example](http://www.deeplearning.net/software/theano/tutorial/using_gpu.html#testing-theano-with-gpu).
If I reinstall the latest version (`pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git
`) after the first import and the driver tests, this example works too.

**Comment by JesseLivezey** [comment]
Should be fixed by #4489

**Comment by tboquet** [comment]
As I posted, I have the git revision right after #4489 and it is still happening.

**Comment by nouiz** [comment]
Be sure to uninstall Theano and make sure you can't import it. Then update/install again. You probably have different version installed.

**Comment by tboquet** [comment]
@nouiz you where right, I was not using the latest dev version.
I just rebuilt and pulled my image and everything is fine now. I mixed the different versions somewhere in the process. Thank you!
