### ISSUE TITLE
(cublas) Execution failed error 11 (multi gpus, new backend)

### ISSUE THREAD

**Issue by cmyr** [Theano/Theano#4635]
theano 0.9.0dev1.dev-6f97e51d9f94da8486d40578e3f7469e2ff3bfd9
libgpuarray commit https://github.com/abergeron/libgpuarray/commit/c25596981502e42ea555f7c0221505d06a27d44b
python 3.5.1

this is a continuation of #4597.

@abergeron @nouiz I've got this error reproducible without keras.

### code

```python

# these are very stripped down approximations

class DummyDense(object):
    def __init__(self, shape, target=None):
        self.weights = theano.shared(
            value=np.random.random(shape).astype('float32'),
            name='W1',
            strict=False,
            target=target)

class DummySGD(object):
    def __init__(self, lr=0.01, target=None, **kwargs):
        self.lr = theano.shared(np.asarray(lr).astype('float32'))
        self.target = target

    def get_updates(self, params, loss):
        grads = theano.tensor.grad(loss, params)
        self.weights = [
            theano.shared(
                np.zeros(p.get_value().shape, dtype='float32'),
                name=p.name+'_sgd',
                target=self.target) for p in params]
        updates = []
        for p, g, m in zip(params, grads, self.weights):
            v = m - self.lr * g  # velocity
            updates.append((m, v))

            new_p = p + v

            updates.append((p, new_p))
        return updates


# wire it up

X = theano.tensor.TensorType(dtype='float32', broadcastable=(False, False))('X')
y = theano.tensor.TensorType(dtype='float32', broadcastable=(False, False))('y')

d1 = DummyDense((13, 17), 'gpu0')
d2 = DummyDense((17, 5), 'gpu0')

sgd = DummySGD(target='gpu1')

O_1 = theano.tensor.dot(X, d1.weights)
O_2 = theano.tensor.dot(O_1, d2.weights)

output = theano.tensor.nnet.softmax(O_2)
diff = output-y
cost = theano.tensor.sqrt(theano.tensor.sum(diff*diff))
# cost = theano.tensor.sqrt(theano.tensor.sum(output*output))

updates = sgd.get_updates([d1.weights, d2.weights], cost)

f = theano.function([X, y], outputs=output, updates=updates)
result = f(np.random.random((10, 13)).astype('float32'), np.random.random((10, 5)).astype('float32'))
```

### output:

```python
---------------------------------------------------------------------------
GpuArrayException                         Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    898             outputs =\
--> 899                 self.fn() if output_subset is None else\
    900                 self.fn(output_subset=output_subset)

pygpu/blas.pyx in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:1595)()

GpuArrayException: (b'(cublas) Execution failed.', 11)

During handling of the above exception, another exception occurred:

GpuArrayException                         Traceback (most recent call last)
<ipython-input-11-bc8bd83b980e> in <module>()
     18 
     19 f = theano.function([X, y], outputs=output, updates=updates)
---> 20 result = f(np.random.random((10, 13)).astype('float32'), np.random.random((10, 5)).astype('float32'))

/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    910                     node=self.fn.nodes[self.fn.position_of_error],
    911                     thunk=thunk,
--> 912                     storage_map=getattr(self.fn, 'storage_map', None))
    913             else:
    914                 # old-style linkers raise their own exceptions

/usr/local/lib/python3.5/dist-packages/theano/gof/link.py in raise_with_op(node, thunk, exc_info, storage_map)
    315         # extra long error message in that case.
    316         pass
--> 317     reraise(exc_type, exc_value, exc_trace)
    318 
    319 

/usr/lib/python3/dist-packages/six.py in reraise(tp, value, tb)
    533     def reraise(tp, value, tb=None):
    534         if value.__traceback__ is not tb:
--> 535             raise value.with_traceback(tb)
    536         raise value
    537 

/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    897         try:
    898             outputs =\
--> 899                 self.fn() if output_subset is None else\
    900                 self.fn(output_subset=output_subset)
    901         except Exception:

pygpu/blas.pyx in pygpu.blas.pygpu_blas_rgemm (pygpu/blas.c:1595)()

GpuArrayException: (b'(cublas) Execution failed.', 11)
Apply node that caused the error: GpuDot22(GpuFromHost<gpu0>.0, W1)
Toposort index: 8
Inputs types: [GpuArrayType<gpu0>(float32, (False, False)), GpuArrayType<gpu0>(float32, (False, False))]
Inputs shapes: [(10, 13), (13, 17)]
Inputs strides: [(52, 4), (68, 4)]
Inputs values: ['not shown', 'not shown']
Inputs type_num: [11, 11]
Outputs clients: [[GpuDot22(GpuDot22.0, W1)]]

Debugprint of the apply node: 
GpuDot22 [id A] <GpuArrayType<gpu0>(float32, (False, False))> ''   
 |GpuFromHost<gpu0> [id B] <GpuArrayType<gpu0>(float32, (False, False))> ''   
 | |X [id C] <TensorType(float32, matrix)>
 |W1 [id D] <GpuArrayType<gpu0>(float32, (False, False))>

Storage map footprint:
 - W1_sgd, Shared Input, Shape: (13, 17), ElemSize: 4 Byte(s), TotalSize: 884 Byte(s)
 - W1, Shared Input, Shape: (13, 17), ElemSize: 4 Byte(s), TotalSize: 884 Byte(s)
 - GpuFromHost<gpu0>.0, Shape: (10, 13), ElemSize: 4 Byte(s), TotalSize: 520 Byte(s)
 - X, Input, Shape: (10, 13), ElemSize: 4 Byte(s), TotalSize: 520 Byte(s)
 - W1, Shared Input, Shape: (17, 5), ElemSize: 4 Byte(s), TotalSize: 340 Byte(s)
 - W1_sgd, Shared Input, Shape: (17, 5), ElemSize: 4 Byte(s), TotalSize: 340 Byte(s)
 - y, Input, Shape: (10, 5), ElemSize: 4 Byte(s), TotalSize: 200 Byte(s)
 - TensorConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuArrayConstant{[[ 0.5]]}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - <TensorType(float32, scalar)>, Shared Input, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 TotalSize: 3700.0 Byte(s) 0.000 GB
 TotalSize inputs: 3180.0 Byte(s) 0.000 GB
```

let me know if there's anything I can do to help!

**Comment by abergeron** [comment]
I actually found a bug in my code.  This PR should fix it: https://github.com/Theano/libgpuarray/pull/196

**Comment by cmyr** [comment]
great, I'll give it a spin.

**Comment by cmyr** [comment]
okay that has cleared up my test case, but I'm still getting issues with my actual code. 😞 My current failing case, in keras (SGD2 is essentially the DummySGD from the original example):

```python
X = np.random.random((32, 13))
y = np.random.random((32, 5))

model = Sequential()
with keras.device('gpu0'):
    model.add(Dense(output_dim=5, input_dim=13, bias=False))
model.compile(loss="mse", optimizer=SGD2())

with keras.device('gpu1'):
    print(model.train_on_batch(X, y))
```

this produces:

```python
---------------------------------------------------------------------------
GpuArrayException                         Traceback (most recent call last)
/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    898             outputs =\
--> 899                 self.fn() if output_subset is None else\
    900                 self.fn(output_subset=output_subset)

pygpu/gpuarray.pyx in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:8778)()

pygpu/gpuarray.pyx in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:6109)()

GpuArrayException: b'invalid resource handle'

During handling of the above exception, another exception occurred:

GpuArrayException                         Traceback (most recent call last)
<ipython-input-9-a30794fef157> in <module>()
      1 with keras.device('gpu1'):
----> 2     print(model.train_on_batch(X, y))

/home/xs/labs/keras/keras/models.py in train_on_batch(self, x, y, class_weight, sample_weight, **kwargs)
    498         return self.model.train_on_batch(x, y,
    499                                          sample_weight=sample_weight,
--> 500                                          class_weight=class_weight)
    501 
    502     def test_on_batch(self, x, y,

/home/xs/labs/keras/keras/engine/training.py in train_on_batch(self, x, y, sample_weight, class_weight)
   1190             ins = x + y + sample_weights
   1191         self._make_train_function()
-> 1192         outputs = self.train_function(ins)
   1193         if len(outputs) == 1:
   1194             return outputs[0]

/home/xs/labs/keras/keras/backend/theano_backend.py in __call__(self, inputs)
    533     def __call__(self, inputs):
    534         assert type(inputs) in {list, tuple}
--> 535         return self.function(*inputs)
    536 
    537 

/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    910                     node=self.fn.nodes[self.fn.position_of_error],
    911                     thunk=thunk,
--> 912                     storage_map=getattr(self.fn, 'storage_map', None))
    913             else:
    914                 # old-style linkers raise their own exceptions

/usr/local/lib/python3.5/dist-packages/theano/gof/link.py in raise_with_op(node, thunk, exc_info, storage_map)
    315         # extra long error message in that case.
    316         pass
--> 317     reraise(exc_type, exc_value, exc_trace)
    318 
    319 

/usr/lib/python3/dist-packages/six.py in reraise(tp, value, tb)
    533     def reraise(tp, value, tb=None):
    534         if value.__traceback__ is not tb:
--> 535             raise value.with_traceback(tb)
    536         raise value
    537 

/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    897         try:
    898             outputs =\
--> 899                 self.fn() if output_subset is None else\
    900                 self.fn(output_subset=output_subset)
    901         except Exception:

pygpu/gpuarray.pyx in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:8778)()

pygpu/gpuarray.pyx in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:6109)()

GpuArrayException: b'invalid resource handle'
Apply node that caused the error: GpuDimShuffle{1,0}(GpuFromHost<gpu1>.0)
Toposort index: 4
Inputs types: [GpuArrayType<gpu1>(float32, (False, False))]
Inputs shapes: [(32, 13)]
Inputs strides: [(52, 4)]
Inputs values: ['not shown']
Inputs type_num: [11]
Outputs clients: [[GpuDot22(GpuDimShuffle{1,0}.0, GpuElemwise{mul}[]<gpuarray>.0)]]

Debugprint of the apply node: 
GpuDimShuffle{1,0} [id A] <GpuArrayType<gpu1>(float32, (False, False))> ''   
 |GpuFromHost<gpu1> [id B] <GpuArrayType<gpu1>(float32, (False, False))> ''   
   |dense_input_1 [id C] <TensorType(float32, matrix)>

Storage map footprint:
 - GpuFromHost<gpu1>.0, Shape: (32, 13), ElemSize: 4 Byte(s), TotalSize: 1664 Byte(s)
 - dense_input_1, Input, Shape: (32, 13), ElemSize: 4 Byte(s), TotalSize: 1664 Byte(s)
 - GpuElemwise{sqr,no_inplace}.0, Shape: (32, 5), ElemSize: 4 Byte(s), TotalSize: 640 Byte(s)
 - dense_1_target, Input, Shape: (32, 5), ElemSize: 4 Byte(s), TotalSize: 640 Byte(s)
 - GpuElemwise{sub,no_inplace}.0, Shape: (32, 5), ElemSize: 4 Byte(s), TotalSize: 640 Byte(s)
 - dense_1_W, Shared Input, Shape: (13, 5), ElemSize: 4 Byte(s), TotalSize: 260 Byte(s)
 - dense_1_W_optimizer, Shared Input, Shape: (13, 5), ElemSize: 4 Byte(s), TotalSize: 260 Byte(s)
 - dense_1_sample_weights, Input, Shape: (32,), ElemSize: 4 Byte(s), TotalSize: 128 Byte(s)
 - GpuElemwise{true_div,no_inplace}.0, Shape: (32,), ElemSize: 4 Byte(s), TotalSize: 128 Byte(s)
 - Constant{-1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - GpuElemwise{Cast{float32}}[]<gpuarray>.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - HostFromGpu(gpuarray).0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuArrayConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuDimShuffle{x}.0, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - GpuArrayConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuArrayConstant{[[2]]}, Shape: (1, 1), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 6061.0 Byte(s) 0.000 GB
 TotalSize inputs: 2977.0 Byte(s) 0.000 GB
```

and the following graph:
![theano_simple_sg2_crash](https://cloud.githubusercontent.com/assets/3330916/16132179/0c16df0c-33e0-11e6-8c16-0ee216bec3b5.png)

**Comment by cmyr** [comment]
I will add that with a slightly more complicated model (one involving a second Dense layer) I'm still getting the error message of parent issue.

**Comment by abergeron** [comment]
Try it under cuda-memcheck.  This will tell us if we hit API errors.

**Comment by cmyr** [comment]
cuda-memcheck returned `No CUDA-MEMCHECK results found`

**Comment by abergeron** [comment]
What command did you run?

It should look like this:
```
THEANO_FLAGS=<some flags> cuda-memcheck python script.py
```

**Comment by cmyr** [comment]
I didn't pass any theano args; there's some stuff in my .theanorc:
```
[global]
#device = gpu0
floatX = float32
contexts = gpu0->cuda0;gpu1->cuda1;gpu2->cuda2;gpu3->cuda3

[cuda]
root = /usr/local/cuda
```

and I ran `cuda-memcheck python3 theano_debug3.py &> res_handle_memcheck.txt`

complete output:

```
Using Theano backend.
Mapped name gpu0 to device cuda0: Tesla K80
Using cuDNN version 5004 on context gpu0
Mapped name gpu1 to device cuda1: Tesla K80
Using cuDNN version 5004 on context gpu1
Mapped name gpu2 to device cuda2: Tesla K80
Using cuDNN version 5004 on context gpu2
Mapped name gpu3 to device cuda3: Tesla K80
Using cuDNN version 5004 on context gpu3
using keras version 1.0.4 from /home/user/labs/keras/keras
using theano version 0.9.0dev1.dev-6f97e51d9f94da8486d40578e3f7469e2ff3bfd9
$WHIRLSCAPE_LABS_DATA_DIR env var not set, using /home/user/whirlscape_labs_data
/home/user/labs/keras/keras/backend/theano_backend.py:531: UserWarning: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 2 is not part of the computational graph needed to compute the outputs: dense_1_sample_weights.
To make this warning into an error, you can pass the parameter on_unused_input='raise' to theano.function. To disable it completely, use on_unused_input='ignore'.
  **kwargs)
dense_1_W
creating variable  dense_1_W (13, 5) on device  gpu0
dense_1_W_optimizer
creating variable  dense_1_W_optimizer (13, 5) on device  gpu1
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 899, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 618, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:8778)
  File "pygpu/gpuarray.pyx", line 349, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:6109)
pygpu.gpuarray.GpuArrayException: b'invalid resource handle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "theano_debug3.py", line 55, in <module>
    print(model.train_on_batch(X, y))
  File "/home/user/labs/keras/keras/models.py", line 500, in train_on_batch
    class_weight=class_weight)
  File "/home/user/labs/keras/keras/engine/training.py", line 1192, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/user/labs/keras/keras/backend/theano_backend.py", line 535, in __call__
    return self.function(*inputs)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 912, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python3.5/dist-packages/theano/gof/link.py", line 317, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib/python3/dist-packages/six.py", line 535, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/theano/compile/function_module.py", line 899, in __call__
    self.fn() if output_subset is None else\
  File "pygpu/gpuarray.pyx", line 618, in pygpu.gpuarray.pygpu_copy (pygpu/gpuarray.c:8778)
  File "pygpu/gpuarray.pyx", line 349, in pygpu.gpuarray.array_copy (pygpu/gpuarray.c:6109)
pygpu.gpuarray.GpuArrayException: b'invalid resource handle'
Apply node that caused the error: GpuDimShuffle{1,0}(GpuFromHost<gpu1>.0)
Toposort index: 4
Inputs types: [GpuArrayType<gpu1>(float32, (False, False))]
Inputs shapes: [(32, 13)]
Inputs strides: [(52, 4)]
Inputs values: ['not shown']
Inputs type_num: [11]
Outputs clients: [[GpuDot22(GpuDimShuffle{1,0}.0, GpuElemwise{mul}[]<gpuarray>.0)]]

Debugprint of the apply node:
GpuDimShuffle{1,0} [id A] <GpuArrayType<gpu1>(float32, (False, False))> ''
 |GpuFromHost<gpu1> [id B] <GpuArrayType<gpu1>(float32, (False, False))> ''
   |dense_input_1 [id C] <TensorType(float32, matrix)>

Storage map footprint:
 - GpuFromHost<gpu1>.0, Shape: (32, 13), ElemSize: 4 Byte(s), TotalSize: 1664 Byte(s)
 - dense_input_1, Input, Shape: (32, 13), ElemSize: 4 Byte(s), TotalSize: 1664 Byte(s)
 - GpuElemwise{sub,no_inplace}.0, Shape: (32, 5), ElemSize: 4 Byte(s), TotalSize: 640 Byte(s)
 - GpuElemwise{sqr,no_inplace}.0, Shape: (32, 5), ElemSize: 4 Byte(s), TotalSize: 640 Byte(s)
 - dense_1_target, Input, Shape: (32, 5), ElemSize: 4 Byte(s), TotalSize: 640 Byte(s)
 - dense_1_W, Shared Input, Shape: (13, 5), ElemSize: 4 Byte(s), TotalSize: 260 Byte(s)
 - dense_1_W_optimizer, Shared Input, Shape: (13, 5), ElemSize: 4 Byte(s), TotalSize: 260 Byte(s)
 - dense_1_sample_weights, Input, Shape: (32,), ElemSize: 4 Byte(s), TotalSize: 128 Byte(s)
 - GpuElemwise{true_div,no_inplace}.0, Shape: (32,), ElemSize: 4 Byte(s), TotalSize: 128 Byte(s)
 - Constant{0}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - Constant{-1}, Shape: (), ElemSize: 8 Byte(s), TotalSize: 8.0 Byte(s)
 - GpuElemwise{Cast{float32}}[]<gpuarray>.0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuDimShuffle{x}.0, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - GpuArrayConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuArrayConstant{1.0}, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - HostFromGpu(gpuarray).0, Shape: (), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - GpuArrayConstant{[[2]]}, Shape: (1, 1), ElemSize: 1 Byte(s), TotalSize: 1 Byte(s)
 TotalSize: 6061.0 Byte(s) 0.000 GB
 TotalSize inputs: 2977.0 Byte(s) 0.000 GB

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
========= CUDA-MEMCHECK
========= Error: process didn't terminate successfully
=========        The application may have hit an error when dereferencing Unified Memory from the host. Please rerun the application under cuda-gdb or Nsight Eclipse Edition to catch host side errors.
========= Internal error (20)
========= No CUDA-MEMCHECK results found
```

**Comment by cmyr** [comment]
okay, something else that's weird:

keras lazily compiles three functions, for training, testing, and predicting.

if I call the predict function before the train function, I get the `cublas Exception failed` error. If I don't, and call the train function first, I get the `invalid resource handle` error.

The output above is for the second case. The first case, run through cuda-memcheck, produces no errors.

**Comment by abergeron** [comment]
What version of cuda and the driver do you have?

**Comment by cmyr** [comment]
Cuda compilation tools, release 7.5, V7.5.17
