### ISSUE TITLE
bug pretty printing subtensor op

### ISSUE THREAD

**Issue by khaotik** [Theano/Theano#5388]
```
import theano as th
#Using cuDNN version 5105 on context None
#Mapped name None to device cuda: GeForce GTX 750 Ti (0000:01:00.0)
x = th.tensor.vector()
y = x[1]
th.pp(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/printing.py", line 616, in __call__
    return self.process(*args)
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/printing.py", line 548, in process
    return self.printers_dict[type(r.owner.op)].process(r, pstate)
  File "/home/khaotik/WKSP_DL/dev/Theano/theano/tensor/subtensor.py", line 972, in process
    inbrack_pstate = pstate.clone(precedence=-1000)
AttributeError: 'PrinterState' object has no attribute 'clone'
```

**Comment by nouiz** [comment]
thanks for the report. This PR should fix this:

https://github.com/Theano/Theano/pull/5389

And also fix a display issue related to that case.

**Comment by ritheshkumar95** [comment]
Hey Fred, Arnaud!
Sadly, I think this issue isn't fixed. I wanted to pretty print the gradients.
I'm still getting this issue:
[debug_log.txt](https://github.com/Theano/Theano/files/754585/debug_log.txt)
^I attached a log file containing the stack-trace. 

PS: I'm running the latest version of theano. (and i verified that my version merged the PR which you have linked above)

**Comment by nouiz** [comment]
I pushed a fix to this PR: https://github.com/Theano/Theano/pull/5508
