### ISSUE TITLE
In dnn.py there is no operation 'sum' while it is already in pooling operation 

### ISSUE THREAD

**Issue by fsalmasri** [Theano/Theano#5509]
In dnn.py there is no operation 'sum' while it is already in pooling operation

**Comment by nouiz** [comment]
I don't understand. Can you explain more? Do you talk about the reduction sum? The sum pooling?

cudnn itself only support the max and average pooling. So we can't have it support the sum pooling. But from memory, we have code on the GPU that support the sum pooling without cudnn. So it should work on the GPU.

What do you want from this?

**Comment by fsalmasri** [comment]
with reference to this page http://deeplearning.net/software/theano_versions/dev/library/tensor/signal/pool.html 

pool_2d have the mode 'sum' but when run it on GPU it gives an error that this mood doesn't exist in the file dnn.py 

I want to apply sum instead of average or max

**Comment by aam-at** [comment]
It seems that pooling operation is lifted to GpuDnnPool even when `mode == 'sum`'. It will require some changes to dnn optimizations. @fsalmasri you can use `dnn_pool` which implements sum pooling.

**Comment by lamblin** [comment]
This should have already been fixed in #4932.
Can you confirm that you are using the latest development version from GitHub?

**Comment by nouiz** [comment]
As no news and should be fixed, closing.

**Comment by fsalmasri** [comment]
I'm using theano 0.9 and it is not fixed I moved to dnn_pool

**Comment by nouiz** [comment]
That version isn't released yet. Can you update to the dev version again
and give us the git commit you used for your Theano with the full error
message.

Le mar. 7 mars 2017 14:05, Feras Almasri <notifications@github.com> a
écrit :
