### ISSUE TITLE
Segmentation Fault When training with a big dataset

### ISSUE THREAD

**Issue by afshinrahimi** [Theano/Theano#5525]
I'm running a Custom MLP with Theano (using Lasagne) and I can run it over a small (input shape 10kx10k) and medium (input shape 400k_200k) but when I run it over a larger dataset (input shape 1.3Mk_100k) it gives me the segmentation fault error when it starts training. The memory starts to grow and then it crashes. I have 500GB of memory and when it gets to less than 20% of memory it throws the segmentation fault error. I'm using cpu and my .theanorc looks like this:

```
[global]
OMP_NUM_THREADS=4
openmp=True
floatX = float64
#profile_memory=True
#profile=True
device=cpu
[blas] 
ldflags=-L/usr/lib/  -lopenblas  -lblas 
```

Note that the input matrices are sparse and I can't do mini-batch and have to do **full batch**.

I used gdb to find where the error occurs and the output is:

```
Thread 17 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3d31700 (LWP 27105)]
(anonymous namespace)::__struct_compiled_op_1b42432866be1c904afdc4503a8345e1::run ()
    at /home/user1/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpB1iBsD/mod.cpp:518
518                 V1_i = V3_i + V5_i;

#0  (anonymous namespace)::__struct_compiled_op_5c38a1b25524822864d2313292bdfdc6::run ()
    at /home/arahimi/.theano/compiledir_Linux-4.4--generic-x86_64-with-Ubuntu-16.04-xenial-x86_64-2.7.12-64/tmpLIG_F8/mod.cpp:518
#1  0x00007fffce85d43e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#2  0x00007ffff7bc16ba in start_thread (arg=0x7fffeed2f700) at pthread_create.c:333
#3  0x00007ffff78f782d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

```
 
Theano, Scipy and Numpy versions:
```
t>>> theano.__version__
'0.9.0beta1.dev-RELEASE'
>>> scipy.__version__
'0.18.1'
>>> numpy.__version__
'1.12.0'
```

I tried with older versions and then I updated to the dev versions but the problem exists.

Theano config is attached.
Also the code that builds the model is attached.

I commented all other operations in the custom layer and left only S.dot(input, w) but the error still exists:
`activation = S.dot(input, self.W)`

where input is a csr sparse matrix 1386766 X 138640 and W is hidden layer parameters with size 138640 X 3000 where 3000 is hidden layer size.
**When I decrease the hidden layer size from 3000 to 1000 it works.**

Given that I still have enough memory, why I can't use higher hidden layer sizes?

[mlpconv_python.txt](https://github.com/Theano/Theano/files/765365/mlpconv_python.txt)

[theano_config.txt](https://github.com/Theano/Theano/files/765364/theano_config.txt)

**Comment by lamblin** [comment]
What happens if you disable openmp? Does it still crash?
Also, what if you run the minimal example (with only `S.dot(...)`) disabling the compilation of C code (`gxx = ""` in the config flags)?

**Comment by lamblin** [comment]
Also, can you try with the fix in #5553?

**Comment by afshinrahimi** [comment]
I tried the suggestions:
set openmp=False in .theanorc
set gxx="" in .theanorc
commented other computations except S.dot(...)).
and also applied fix #5553.

It still crashes with segmentation fault.

**Comment by rebecca-palmer** [comment]
Does a sparse product this size work in scipy?

Is the problem the number of elements in W, or the number of elements in the output? (try reducing the first dimension of the input)

**Comment by nouiz** [comment]
To help us identify the op that cause the problem, can you use MonitorMode
in the function that segfault? Use this as an example:

http://deeplearning.net/software/theano/tutorial/debug_faq.html#how-do-i-step-through-a-compiled-function

You can use just the inspect_inputs. Modify it to only print the shape of
the value, not the value themself. Something like:

def inspect_inputs(i, node, fn):
    print(i, node, "input(s) value(s):", [input[0].shape for input in
fn.inputs],
          end='')

**Comment by afshinrahimi** [comment]
I can confirm that I multiplied the exact same matrix X (input) to a random w with the same size in scipy and it worked without a problem (X.dot(w)).

I will try the MonitorMode and report the results asap.

**Comment by afshinrahimi** [comment]
MonitorMode logs:

```
0 InplaceDimShuffle{x}(TensorConstant{0.0}) input(s) shape(s): [()] output(s) shape(s): [(1,)]
1 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(930,)] output(s) shape(s): [(1, 930)]
2 Elemwise{sgn}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
3 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
4 InplaceDimShuffle{1,0}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(930, 3000)]
5 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(3000,)] output(s) shape(s): [(1, 3000)]
6 Elemwise{sgn}(W) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [(138640, 3000)]
7 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [(138640, 3000)]
8 SparseDot(SparseVariable{csr,float32}, W) input(s) shape(s): [(1386766, 138640), (138640, 3000)] output(s) shape(s): [(1386766, 3000)]
9 SparseTranspose(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 138640)] output(s) shape(s): [(138640, 1386766)]
10 SparseTranspose(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 1386766)] output(s) shape(s): [(1386766, 1386766)]
11 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.999}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (930,)] output(s) shape(s): [(930,)]
12 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.9}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (930,)] output(s) shape(s): [(930,)]
13 Elemwise{pow,no_inplace}(W, TensorConstant{(1, 1) of 2}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
14 Elemwise{pow,no_inplace}(W, TensorConstant{(1, 1) of 2}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
15 Elemwise{pow}(W, TensorConstant{(1, 1) of 1}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
16 Elemwise{pow}(W, TensorConstant{(1, 1) of 1}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
17 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.999}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (3000, 930)] output(s) shape(s): [(3000, 930)]
18 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.9}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (3000, 930)] output(s) shape(s): [(3000, 930)]
19 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.999}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (3000,)] output(s) shape(s): [(3000,)]
20 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.9}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (3000,)] output(s) shape(s): [(3000,)]
21 Elemwise{add,no_inplace}(<TensorType(float32, scalar)>, TensorConstant{1}) input(s) shape(s): [(), ()] output(s) shape(s): [()]
22 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.999}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (138640, 3000)] output(s) shape(s): [(138640, 3000)]
23 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.9}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (138640, 3000)] output(s) shape(s): [(138640, 3000)]
24 Elemwise{second}(Elemwise{abs_,no_inplace}.0, TensorConstant{(1, 1) of 2.5e-06}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
25 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
26 Elemwise{second}(Elemwise{abs_,no_inplace}.0, TensorConstant{(1, 1) of 2.5e-06}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
27 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [()]
28 SparseDot(SparseVariable{csr,float32}, SparseDot.0) input(s) shape(s): [(1386766, 1386766), (1386766, 3000)] output(s) shape(s): [(1386766, 3000)]
29 Elemwise{second}(Elemwise{pow,no_inplace}.0, TensorConstant{(1, 1) of 2.5e-06}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
30 Sum{acc_dtype=float64}(Elemwise{pow,no_inplace}.0) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
31 Elemwise{second}(Elemwise{pow,no_inplace}.0, TensorConstant{(1, 1) of 2.5e-06}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
32 Sum{acc_dtype=float64}(Elemwise{pow,no_inplace}.0) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [()]
33 Elemwise{pow,no_inplace}(TensorConstant{0.899999976158}, Elemwise{add,no_inplace}.0) input(s) shape(s): [(), ()] output(s) shape(s): [()]
34 Elemwise{pow,no_inplace}(TensorConstant{0.999000012875}, Elemwise{add,no_inplace}.0) input(s) shape(s): [(), ()] output(s) shape(s): [()]
35 Elemwise{mul}(Elemwise{second}.0, Elemwise{sgn}.0) input(s) shape(s): [(3000, 930), (3000, 930)] output(s) shape(s): [(3000, 930)]
36 Elemwise{add,no_inplace}(TensorConstant{0}, Sum{acc_dtype=float64}.0) input(s) shape(s): [(), ()] output(s) shape(s): [()]
37 Elemwise{mul}(Elemwise{second}.0, Elemwise{sgn}.0) input(s) shape(s): [(138640, 3000), (138640, 3000)] output(s) shape(s): [(138640, 3000)]
38 Elemwise{add,no_inplace}(TensorConstant{0}, Sum{acc_dtype=float64}.0) input(s) shape(s): [(), ()] output(s) shape(s): [()]
39 Elemwise{add,no_inplace}(SparseDot.0, InplaceDimShuffle{x,0}.0) input(s) shape(s): [(1386766, 3000), (1, 3000)]Segmentation fault (core dumped)
```

**Comment by afshinrahimi** [comment]
It again happens when I commented the custom part of the layers `actication = S.dot(H, activation) ` and again the error is when adding the bias term:

```
0 InplaceDimShuffle{x}(TensorConstant{0.0}) input(s) shape(s): [()] output(s) shape(s): [(1,)]
1 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(930,)] output(s) shape(s): [(1, 930)]
2 Elemwise{sgn}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
3 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
4 InplaceDimShuffle{1,0}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(930, 3000)]
5 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(3000,)] output(s) shape(s): [(1, 3000)]
6 Elemwise{sgn}(W) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [(138640, 3000)]
7 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [(138640, 3000)]
8 SparseDot(SparseVariable{csr,float32}, W) input(s) shape(s): [(1386766, 138640), (138640, 3000)] output(s) shape(s): [(1386766, 3000)]
9 SparseTranspose(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 138640)] output(s) shape(s): [(138640, 1386766)]
10 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.999}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (930,)] output(s) shape(s): [(930,)]
11 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.9}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (930,)] output(s) shape(s): [(930,)]
12 Elemwise{pow,no_inplace}(W, TensorConstant{(1, 1) of 2}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
13 Elemwise{pow,no_inplace}(W, TensorConstant{(1, 1) of 2}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
14 Elemwise{pow}(W, TensorConstant{(1, 1) of 1}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
15 Elemwise{pow}(W, TensorConstant{(1, 1) of 1}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
16 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.999}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (3000, 930)] output(s) shape(s): [(3000, 930)]
17 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.9}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (3000, 930)] output(s) shape(s): [(3000, 930)]
18 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.999}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (3000,)] output(s) shape(s): [(3000,)]
19 Elemwise{mul,no_inplace}(TensorConstant{(1,) of 0.9}, <TensorType(float32, vector)>) input(s) shape(s): [(1,), (3000,)] output(s) shape(s): [(3000,)]
20 Elemwise{add,no_inplace}(<TensorType(float32, scalar)>, TensorConstant{1}) input(s) shape(s): [(), ()] output(s) shape(s): [()]
21 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.999}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (138640, 3000)] output(s) shape(s): [(138640, 3000)]
22 Elemwise{mul,no_inplace}(TensorConstant{(1, 1) of 0.9}, <TensorType(float32, matrix)>) input(s) shape(s): [(1, 1), (138640, 3000)] output(s) shape(s): [(138640, 3000)]
23 Elemwise{second}(Elemwise{abs_,no_inplace}.0, TensorConstant{(1, 1) of 2.5e-06}) input(s) shape(s): [(3000, 930), (1, 1)] output(s) shape(s): [(3000, 930)]
24 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
25 Elemwise{second}(Elemwise{abs_,no_inplace}.0, TensorConstant{(1, 1) of 2.5e-06}) input(s) shape(s): [(138640, 3000), (1, 1)] output(s) shape(s): [(138640, 3000)]
26 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [()]
27 Elemwise{add,no_inplace}(SparseDot.0, InplaceDimShuffle{x,0}.0) input(s) shape(s): [(1386766, 3000), (1, 3000)]Segmentation fault (core dumped)
```

**Comment by rebecca-palmer** [comment]
That's sparse + dense with >2**31 elements, which is likely to trigger an integer overflow at [pos = row * Yi + col * Yj;](https://github.com/Theano/Theano/blob/master/theano/sparse/opt.py#L154) (which uses 32-bit signed integers, and where Yi, Yj are strides in elements, i.e. typically num_cols, 1).

Though that does leave the question of why gxx="" didn't help...

**Comment by afshinrahimi** [comment]
I added the `gxx=""` in the general section of _.theanorc_ file if that's right, but didn't solve the issue.

**Comment by afshinrahimi** [comment]
Also when I turn on _dropout_ an explicit 32-bit error is thrown:

```
0 Shape_i{0}(<TensorType(int32, vector)>) input(s) shape(s): [(1366766,)] output(s) shape(s): [()]
1 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(930,)] output(s) shape(s): [(1, 930)]
2 Shape_i{1}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
3 Elemwise{sgn}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
4 InplaceDimShuffle{1,0}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(930, 3000)]
5 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
6 Shape_i{1}(W) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [()]
7 Shape_i{0}(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 1386766)] output(s) shape(s): [()]
8 SparseTranspose(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 1386766)] output(s) shape(s): [(1386766, 1386766)]
9 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(3000,)] output(s) shape(s): [(1, 3000)]
10 MulSD(SparseVariable{csr,float32}, TensorConstant{2.0}) input(s) shape(s): [(1386766, 138640), ()] output(s) shape(s): [(1386766, 138640)]
11 Shape_i{1}(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 138640)] output(s) shape(s): [()]
12 Shape_i{0}(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 138640)] output(s) shape(s): [()]
13 Elemwise{Add}[(0, 1)](TensorConstant{1.0}, <TensorType(float32, scalar)>) input(s) shape(s): [(), ()] output(s) shape(s): [()]
14 Elemwise{Cast{float32}}(Shape_i{0}.0) input(s) shape(s): [()] output(s) shape(s): [()]
15 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
16 MakeVector{dtype='int64'}(Shape_i{0}.0, Shape_i{1}.0) input(s) shape(s): [(), ()] output(s) shape(s): [(2,)]
17 Alloc(TensorConstant{(1, 1) of 0.0}, Shape_i{0}.0, Shape_i{1}.0) input(s) shape(s): [(1, 1), (), ()] output(s) shape(s): [(1386766, 930)]
18 CSMProperties(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 138640)] output(s) shape(s): [(60775448,), (60775448,), (1386767,), (2,)]
19 MakeVector{dtype='int64'}(Shape_i{0}.0, Shape_i{1}.0) input(s) shape(s): [(), ()] output(s) shape(s): [(2,)]
20 Elemwise{Composite{((i0 * sqrt((i1 - (i2 ** i3)))) / (i1 - (i4 ** i3)))}}(TensorConstant{0.00400000018999}, TensorConstant{1.0}, TensorConstant{0.999000012875}, Elemwise{Add}[(0, 1)].0, TensorConstant{0.899999976158}) input(s) shape(s): [(), (), (), (), ()] output(s) shape(s): [()]
21 InplaceDimShuffle{x}(Elemwise{Cast{float32}}.0) input(s) shape(s): [()] output(s) shape(s): [(1,)]
22 mrg_uniform{TensorType(float32, matrix),inplace}(<TensorType(int32, matrix)>, MakeVector{dtype='int64'}.0) input(s) shape(s): [(15360, 6), (2,)]Traceback (most recent call last):
  File "tensormain.py", line 483, in <module>
    main_mlpconv(data, batch=args.batch, hidden=args.hidden, regularization=args.regularization)
  File "tensormain.py", line 237, in main_mlpconv
    clf.fit(X, train_indices, dev_indices, test_indices, Y, H)
  File "/home/usr1/git/localism/mlpconv.py", line 291, in fit
    l_train, acc_train = self.f_train(x_batch, y_batch, self.H, self.train_indices)
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/compile/function_module.py", line 884, in __call__
    self.fn() if output_subset is None else\
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/gof/link.py", line 1016, in f
    raise_with_op(node, *thunks)
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/gof/link.py", line 1014, in f
    wrapper(i, node, *thunks)
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/gof/link.py", line 1030, in wrapper
    f(*args)
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/compile/monitormode.py", line 73, in eval
    fn()
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/gof/op.py", line 832, in rval
    fill_storage()
  File "/home/usr1/.local/lib/python2.7/site-packages/theano/gof/cc.py", line 1701, in __call__
    reraise(exc_type, exc_value, exc_trace)
  File "<string>", line 2, in reraise
ValueError: rng_mrg cpu-implementation does not support more than (2**31 -1) samples
Apply node that caused the error: mrg_uniform{TensorType(float32, matrix),inplace}(<TensorType(int32, matrix)>, MakeVector{dtype='int64'}.0)

```

**Comment by afshinrahimi** [comment]
I applied fix #5525 but still get the error.

**Comment by lamblin** [comment]
Sorry, that was a typo on my end, it should have been `cxx=""`, not `gxx`.
In any case, thanks @rebecca-palmer for diagnosing the issue.

**Comment by rebecca-palmer** [comment]
With the fix, does it still crash on the same Elemwise{add,no_inplace}, or somewhere else?  There are several more "can't handle array sizes that overflow an int" bugs.

**Comment by afshinrahimi** [comment]
I can confirm that with cxx="" it doesn't throw the segmentation fault but it becomes so slow that I couldn't even run 1 epoch.

To apply the fix I just copied the new fixed opt.py instead of the old one in the theano/sparse/ directory that my python is using.

The error is still at the elementwise{add, no_inplace}:

```
0 Shape_i{0}(<TensorType(int32, vector)>) input(s) shape(s): [(1366766,)] output(s) shape(s): [()]
1 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(930,)] output(s) shape(s): [(1, 930)]
2 Shape_i{1}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
3 Elemwise{sgn}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
4 InplaceDimShuffle{1,0}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(930, 3000)]
5 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(3000, 930)] output(s) shape(s): [(3000, 930)]
6 InplaceDimShuffle{x,0}(b) input(s) shape(s): [(3000,)] output(s) shape(s): [(1, 3000)]
7 Elemwise{abs_,no_inplace}(W) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [(138640, 3000)]
8 SparseDot(SparseVariable{csr,float32}, W) input(s) shape(s): [(1386766, 138640), (138640, 3000)] output(s) shape(s): [(1386766, 3000)]
9 SparseTranspose(SparseVariable{csr,float32}) input(s) shape(s): [(1386766, 138640)] output(s) shape(s): [(138640, 1386766)]
10 Elemwise{Add}[(0, 1)](TensorConstant{1.0}, <TensorType(float32, scalar)>) input(s) shape(s): [(), ()] output(s) shape(s): [()]
11 Elemwise{Cast{float32}}(Shape_i{0}.0) input(s) shape(s): [()] output(s) shape(s): [()]
12 Alloc(TensorConstant{(1, 1) of 0.0}, TensorConstant{1386766}, Shape_i{1}.0) input(s) shape(s): [(1, 1), (), ()] output(s) shape(s): [(1386766, 930)]
13 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(3000, 930)] output(s) shape(s): [()]
14 Sum{acc_dtype=float64}(Elemwise{abs_,no_inplace}.0) input(s) shape(s): [(138640, 3000)] output(s) shape(s): [()]
15 SparseDot(SparseConstant{csr,float32,shape=(1386766, 1386766),nnz=3389128}, SparseDot.0) input(s) shape(s): [(1386766, 1386766), (1386766, 3000)] output(s) shape(s): [(1386766, 3000)]
16 Elemwise{Composite{((i0 * sqrt((i1 - (i2 ** i3)))) / (i1 - (i4 ** i3)))}}(TensorConstant{0.00400000018999}, TensorConstant{1.0}, TensorConstant{0.999000012875}, Elemwise{Add}[(0, 1)].0, TensorConstant{0.899999976158}) input(s) shape(s): [(), (), (), (), ()] output(s) shape(s): [()]
17 InplaceDimShuffle{x}(Elemwise{Cast{float32}}.0) input(s) shape(s): [()] output(s) shape(s): [(1,)]
18 Elemwise{Add}[(0, 0)](SparseDot.0, InplaceDimShuffle{x,0}.0) input(s) shape(s): [(1386766, 3000), (1, 3000)]Segmentation fault (core dumped)
```

was that the correct way of applying the fix? I also deleted the .pyc file but didn't help.

**Comment by nouiz** [comment]
The problem is in the file tensor/elemwise.py

The elemwise op use int internally. So we probably the same fix there as
done in sparse/opt.py. Can you add the printing of input.stride and
addition to input.shape to the MonitorMode printer fct and give us the new
output? It will help see which part of the code need modfication. The
elemwise code is much more complicated then the sparse one.

**Comment by rebecca-palmer** [comment]
I had already been investigating whether there were more such issues elsewhere in Theano (though I hadn't expected them to be involved in your particular problem), but haven't yet had time to write a patch; my current list is:

(Only includes items that actually try to run on too-large data (and hence either segfault or give wrong results), not ones that explicitly error out.  If "error out" means "fall back to Numpy", be aware that [their large-array handling isn't perfect either](https://github.com/numpy/numpy/issues/5533).)

tensor/basic split i, join tensors_lens_sum
tensor/blas Gemm, batch_gemm
tensor/blas_c everything - including overflow on total number of elements (not just single dimension) too big
tensor/elemwise Elemwise i (line 1166)
tensor/elemwise_cgen jumps (line 28), %(ovar)s_loops and iterators (lines 275-6,371), total (335), init_strides(360), stride(380), iterv(412)
tensor/subtensor idx(845)
tensor/signal/pool everything
tensor/nnet not fully checked, but has at least a few
sparse/basic StructuredDotGradCSR/C outer and innermost
sandbox/multinomial everything
sandbox/rng_mrg DotModulo i,j (both times) (is this exposed directly? mrg_* do check, which is the explicit error you're seeing with dropout on)
gpuarray and sandbox/cuda not checked

**Comment by rebecca-palmer** [comment]
Earlier comments imply that that fix *doesn't* actually fix this - can this issue be reopened?

**Comment by abergeron** [comment]
You can probably open another ticket with the list you found (thank for that by the way) so that we can track which file still has problems and which is fixed.

If you feel that reopening this one is best, then do that instead.

**Comment by rebecca-palmer** [comment]
I've pushed some potential elemwise fixes [here](https://github.com/rebecca-palmer/Theano/commits/master), but they haven't been tested yet (and looks like I accidentally pushed them to my master instead of a mergeable branch).

**Comment by afshinrahimi** [comment]
I applied the new fixes:
fix index int32 overflows in elemwise
fix index int32 overflow in sparse.StructuredDotGradCS*

by replacing the whole .py files.
still get the error here:

`
18 Elemwise{Add}[(0, 0)](SparseDot.0, InplaceDimShuffle{x,0}.0) input(s) shape(s): [(1386766, 3000), (1, 3000)]Segmentation fault (core dumped)`


I wanted to print the strides in inspect_input Monitor mode as well like this:

`print(i, node, "input(s) stride(s):", [input[0].stride for input in fn.inputs], end='')`

but it throws an error, I'm not sure how to get the strides to print I also tried input[0].strieds, input[0].strides() didn't find any documentation on that.

If you clarify how to print the strides I'll be able to run the code in Monitor mode and bring the log here.

Thanks.

**Comment by nouiz** [comment]
print(i, node, "input(s) stride(s):", [input.strides for input in fn.inputs], end='')

should print the strides.

@rebecca-palmer you can still make a PR from your master branch. I did a comment on the commit directly in your fork.

thanks

**Comment by afshinrahimi** [comment]
print(i, node, "input(s) stride(s):", [input.strides for input in fn.inputs], end='')

throws this error:
```
  File "/home/usr1/git/localism/mlpconv.py", line 99, in inspect_inputs
    print(i, node, "input(s) stride(s):", [input.strides for input in fn.inputs], end='')
AttributeError: 'list' object has no attribute 'strides'
```

I had also tried with input[0].strides which threw another error.

**Comment by rebecca-palmer** [comment]
Looks like I missed a few int32s - here's [an updated fix](https://github.com/Theano/Theano/compare/master...rebecca-palmer:index_overflow_fixes).  Does this help?

If not, please try a gdb backtrace again, and if it points to a mod.cpp (Theano-generated C code), also post that file.

**Comment by afshinrahimi** [comment]
I can confirm that the fix resolves the issue.
Thank you very much @rebecca-palmer for all the help.

**Comment by afshinrahimi** [comment]
Forgot to say I only applied basic.py not the others and that resolved my issue. Didn't apply other fixes (elemwise.py and elemwise_cgen.py).

**Comment by nouiz** [comment]
I made a PR with that to get travis starting faster:

https://github.com/Theano/Theano/pull/5721

thanks

**Comment by rebecca-palmer** [comment]
> Forgot to say I only applied basic.py not the others

Then it wasn't my updated fix that solved the problem: the theano/sparse/basic.py part of the fix is the same as it was when you said it didn't work, so either something else has changed (and I don't see anything obvious in the history), or (since on the previous attempt you applied both parts) my elemwise fixes actually made things _worse_.

**Comment by afshinrahimi** [comment]
the previsous elemwise fixes are still there. So the previous fixes were already there. The only thing I did was to replace the new (or unchanged) basic.py with the one which I had applied previous fixes on.

Other things changed: I have recently installed Anaconda (though checked numpy, scipy and theano versions and they're the same as before).

The machine I'm working on is shared between a few people so maybe something else changed that I don't know of.

I'm confused what fixed the problem.
