### ISSUE TITLE
Import yields TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by kohr-h** [Theano/Theano#5887]
The first import of Theano (dev version and conda version) fails with this traceback:
```python

  File "[...]/Theano/theano/__init__.py", line 88, in <module>
    from theano.compile import (

  File "[...]/Theano/theano/compile/__init__.py", line 10, in <module>
    from theano.compile.function_module import *

  File "[...]/Theano/theano/compile/function_module.py", line 21, in <module>
    import theano.compile.mode

  File "[...]/Theano/theano/compile/mode.py", line 10, in <module>
    import theano.gof.vm

  File "[...]/Theano/theano/gof/vm.py", line 670, in <module>
    from . import lazylinker_c

  File "[...]/Theano/theano/gof/lazylinker_c.py", line 125, in <module>
    args = cmodule.GCC_compiler.compile_args()

  File "[...]/Theano/theano/gof/cmodule.py", line 2090, in compile_args
    default_compilation_result, default_execution_result = try_march_flag(GCC_compiler.march_flags)

  File "[...]/Theano/theano/gof/cmodule.py", line 1865, in try_march_flag
    flags=cflags, try_run=True)

  File "[...]/Theano/theano/gof/cmodule.py", line 2177, in try_compile_tmp
    comp_args)

  File "[...]/Theano/theano/gof/cmodule.py", line 1798, in _try_compile_tmp
    err += "\n" + str(e)

TypeError: can't concat bytes to str
```
The only function setting the `err` variable is `output_subprocess_Popen` in `misc/windows.py` (BTW I'm working on a Linux machine). That function, in turn, returns a tuple containing the return value from `Popen.communicate()` in the `subprocess` module. The return value of that method is of type `bytes` according to [the documentation](https://docs.python.org/3.5/library/subprocess.html#subprocess.Popen.communicate).

I suspect that this type of issue has the potential to pop up at random places, but for this particular case a simple fix would be to replace the line in question by
```python
err = str(err) + "\n" + str(e)
```

**Comment by nouiz** [comment]
Do you want to make a PR with that to have your name in the history? Otherwise, I can do it.

When you fix that manually, does the rest work for you?

**Comment by kohr-h** [comment]
> Do you want to make a PR with that to have your name in the history? Otherwise, I can do it.

Just put up the PR.



> When you fix that manually, does the rest work for you?

Yes, this fixes the error, just tested it with a fresh conda env.

**Comment by c-f-h** [comment]
I'm getting the same error on Python 3.4 with Theano 0.9.0 installed through pip. Does this mean Theano 0.9.0 is simply broken on Python 3? What are the conditions for this happening? Why was this never caught before?

**Comment by kohr-h** [comment]
> I'm getting the same error on Python 3.4 with Theano 0.9.0 installed through pip. Does this mean Theano 0.9.0 is simply broken on Python 3? What are the conditions for this happening? Why was this never caught before?

IIRC this only occurs on the very first import, subsequent imports seem to take a different route that doesn't invoke this code. Probably some caching thing?

**Comment by c-f-h** [comment]
For me this happened consistently because there was some error related to pygpu not being available, and it tried to format this error every time. So I couldn't import theano at all. For now I patched it as mentioned above and switched to the cpu backend.

**Comment by nouiz** [comment]
It is fixed in the dev version. Just update to it. It is pretty stable, so
you can use it without fear.

It wasn't caught as the problem is in the handling of an error. As our
installation was working when we tested it on windows, we didn't saw that
problem.

**Comment by DomHudson** [comment]
I'm still getting this with brand new environments and `pip install theano` with python 3. Is the recommended action to make the change that @kohr-h described; replacing the offending line with:
```
err = str(err) + "\n" + str(e)
```

**Comment by nouiz** [comment]
pip install install an older installation. Try with 1.0rc1. You can get it
from conda:

https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray)
<https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end(gpuarray>

or from github.

(or you can try to manually patch your 0.9 version that we don't support
anymore)
