### ISSUE TITLE
Python stopped working when using GPU on Windows

### ISSUE THREAD

**Issue by notoraptor** [Theano/Theano#6428]
When I run the following small script on Windows, I get the `program stopped working` dialog box just at the end of the script (after theano function run):
```python
from __future__ import absolute_import, print_function, division

import theano
from theano.gpuarray.tests.config import mode_with_gpu

x = theano.tensor.fvector()
y = x.sum()
f = theano.function([x], y, mode=mode_with_gpu)
theano.printing.debugprint(f)
print(f([1, 2, 3, 4, 5, 6]))
print('ok')
```
Screenshot:

![error-with-gpu-sum](https://user-images.githubusercontent.com/3467054/30559232-f53566b2-9c81-11e7-861d-8aa9b5f4cb18.png)

I don't yet know why this happens. It may be hard to debug.

Also, GPU loading (time before printing `Mapped name None to ...`) is a little slow, even after running the script many times without calling `theano-cache`.

@nouiz @abergeron

**Comment by abergeron** [comment]
This is the windows version of a segfault.  It sometimes happen at the end and I haven't been able to isolate the cause.  However deleting the cache usually gets rid of this.

**Comment by notoraptor** [comment]
Still failing even after a theano cache:

![image](https://user-images.githubusercontent.com/3467054/30563599-5b2d098a-9c90-11e7-90ed-54544d5ce1e1.png)

Ok, so it's a segfault. Quite weird, as this didn't happen before (like, 10 days ago).

I am not sure to be able to find the cause, too.

**Comment by nouiz** [comment]
@notoraptor is this fixed? I recall @abergeron telling me it should be fixed.

**Comment by notoraptor** [comment]
@nouiz it still fails (tested just now):

![still-failing](https://user-images.githubusercontent.com/3467054/31080562-0458d216-a757-11e7-96d1-91577a7610c7.png)

I will spend more time on windows bugs this week.

**Comment by notoraptor** [comment]
A not about memory usage. I run following code once without GPU and once with cuda enabled:
```python
from __future__ import absolute_import, print_function, division

import gc
import psutil
import theano

mode = None

x = theano.tensor.fmatrix()
y = x.dimshuffle(1, 0)
f = theano.function([x], y, mode=mode)
theano.printing.debugprint(f)

a = [[1, 2, 3], [4, 5, 5]]
for i in range(10):
	f(a)
	while gc.collect() > 0:
		pass
	print('  memory use:\t\t\t{:.3f} MiB'.format(
		psutil.Process().memory_info()[0] / float(1024**2)))

print('end.')
```

This is the output:
```

(python2) C:\Users\notoraptor\mila\dev\git\theano>python ../test_with_dimshuffle.py
DeepCopyOp [id A] ''   1
 |InplaceDimShuffle{1,0} [id B] ''   0
   |<TensorType(float32, matrix)> [id C]
  memory use:                   264.383 MiB
  memory use:                   264.391 MiB
  memory use:                   264.395 MiB
  memory use:                   264.398 MiB
  memory use:                   264.402 MiB
  memory use:                   264.402 MiB
  memory use:                   264.402 MiB
  memory use:                   264.402 MiB
  memory use:                   264.402 MiB
  memory use:                   264.402 MiB
end.

(python2) C:\Users\notoraptor\mila\dev\git\theano>env THEANO_FLAGS=device=cuda python ../test_with_dimshuffle.py
Using cuDNN version 7002 on context None
Mapped name None to device cuda: GeForce GTX 1050 (0000:01:00.0)
HostFromGpu(gpuarray) [id A] ''   2
 |InplaceGpuDimShuffle{1,0} [id B] ''   1
   |GpuFromHost<None> [id C] ''   0
     |<TensorType(float32, matrix)> [id D]
  memory use:                   2961.996 MiB
  memory use:                   2962.004 MiB
  memory use:                   2962.008 MiB
  memory use:                   2962.016 MiB
  memory use:                   2962.016 MiB
  memory use:                   2962.016 MiB
  memory use:                   2962.016 MiB
  memory use:                   2962.016 MiB
  memory use:                   2962.016 MiB
  memory use:                   2962.016 MiB
end.
```
Python takes about 3GB of memory when cuda is enabled, vs 264MB when using only CPU. Is it expected ?

Note that same thing seems to occur on Linux, but with less memory (1GB with gpu, about 100MB with CPU).

@nouiz @abergeron @lamblin

**Comment by abergeron** [comment]
This is possibly cuda's fault since it maps the whole GPU address space in the process.  I don't know how that is counted with regards to the various memory reporting APIs.

**Comment by notoraptor** [comment]
@abergeron OK.

About memory reporting APIs, Windows task bar also reports 3GB memory usage for Python:

![ml2](https://user-images.githubusercontent.com/3467054/31089085-cf8a8510-a770-11e7-8018-f993c88a56dc.png)

**Comment by notoraptor** [comment]
Well, the bug cannot be reproduced on jenkins machine (Windows 10, with a GTX 750), and I can not reproduce it on my old machine (Windows 8.1 64 bits, GeForce 840M, with up-to-date driver 385.69).

So, I have this bug only on my work machine (Windows 10 64 bits, GTX 1050, drivers updated [385.69]). Currently, I don't know if it is related to a bad configuration, or to the hardware.

I have re-downloaded the git repository of libgpuarray to have a clean working directory, then I recompiled libgpuarray, but I still have the bug.

@abergeron @nouiz

**Comment by notoraptor** [comment]
Just and update here. I still don't find why I have this segfault, but it seems to occur only with cuda backend, not with opencl backend.

I test with this script:
```python
from __future__ import print_function
import pygpu
import pygpu.blas
import sys

# This script expects device name (e.g. "cuda", "opencl0:0") as parameter.

if len(sys.argv) != 2:
	print('Please specify a device (e.g. "cuda" or "opencl0:0") as script parameter:')
	print('\tpython %s <device>' % sys.argv[0])
	exit(-1)

ctx = pygpu.init(sys.argv[1])

print('Pygpu version:', pygpu.__version__)
print('Device:', ctx.devname)
try:
	print('Unique ID:', ctx.unique_id)
except Exception as e:
	pass

tmp = pygpu.empty((2, 2), dtype='float32', context=ctx)
pygpu.blas.gemm(0, tmp, tmp, 0, tmp, overwrite_c=True)

print('tmp')
del tmp

print('ctx')
del ctx

print('end')
```

For opencl, I use **`clblas`** 2.12 : https://github.com/clMathLibraries/clBLAS/releases

This is test output:
```
(python2) C:\Users\notoraptor\mila\dev\git>python tmp.py cuda
Pygpu version: 0.7.4+0.g65f34a14e.dirty
Device: GeForce GTX 1050
Unique ID: 0000:01:00.0
tmp
ctx

(python2) C:\Users\notoraptor\mila\dev\git>python tmp.py opencl2:0
Pygpu version: 0.7.4+0.g65f34a14e.dirty
Device: GeForce GTX 1050
tmp
ctx
end

(python2) C:\Users\notoraptor\mila\dev\git>
```
Segfault still occurs with `cuda` when freeing ctx, but script runs well until the end with `opencl`.

NB: To correctly test opencl, you need a bug fix in libgpuarray: https://github.com/Theano/libgpuarray/pull/550

@abergeron @nouiz

**Comment by notoraptor** [comment]
An update here. When I try to use gpuarray directly into a C program, everything goes well. So, it seems problem may come from Python side.

This is the C code used:
File `test_gpuarray.cpp`:
```C++
#include <cstdio>
#include <gpuarray/error.h>
#include <gpuarray/blas.h>
#include <gpuarray/array.h>
int main() {
	gpucontext_props* p = NULL;
	gpucontext* ctx = NULL;
	GpuArray tmp;
	size_t tmp_dims[] = {2, 2};
	// Using cuda0.
	const char* kind = "cuda";
	int device_number = 0;
	char devname[256];
	char unique_id[16];
	int err;
	#define CHECKERROR(name) if (err != GA_NO_ERROR) {printf("error " name); return 1;}

	err = gpucontext_props_new(&p);
	CHECKERROR("gpucontext_props_new");

	// This step seems no mandatory: gpucontext_props_alloc_cache(p, initial_cache_size, max_cache_size);

	gpucontext_props_cuda_dev(p, device_number);
	err = gpucontext_init(&ctx, kind, p);
	CHECKERROR("gpucontext_init");
	printf("Context initialized.\n");

	err = gpucontext_property(ctx, GA_CTX_PROP_DEVNAME, devname);
	CHECKERROR("gpucontext_property (devname)");
	err = gpucontext_property(ctx, GA_CTX_PROP_UNIQUE_ID, unique_id);
	CHECKERROR("gpucontext_property (unique id)");
	printf("Device name: %s\n", devname);
	printf("Unique ID: %s\n", unique_id);

	err = GpuArray_empty(&tmp, ctx, GA_FLOAT, 2, tmp_dims, GA_C_ORDER);
	CHECKERROR("GpuArray_empty");

	err = GpuArray_rgemm(cb_no_trans, cb_no_trans, 0, &tmp, &tmp, 0, &tmp, 0);
	CHECKERROR("GpuArray_rgemm");
	printf("Blasted.\n");

	printf("Freeing tmp.\n");
	GpuArray_clear(&tmp);
	printf("Freeing context.\n");
	gpucontext_deref(ctx);
	printf("end.\n");
	return 0;
}
```
Environment variables `CPATH, LIBRARY_PATH, PATH` are correctly set so that g++ can find my latest compiled version of libgpuarray (in `C:\Users\notoraptor\data\libraries`):
```
(python2) C:\Users\notoraptor\mila\dev\git\theano>echo %CPATH%
C:\Users\notoraptor\data\libraries\include;

(python2) C:\Users\notoraptor\mila\dev\git\theano>echo %LIBRARY_PATH%
C:\Users\notoraptor\data\libraries\lib;

(python2) C:\Users\notoraptor\mila\dev\git\theano>echo %PATH%
C:\Users\notoraptor\data\libraries\bin;C:\Users\notoraptor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64;C:\Users\notoraptor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\WinSDK\Bin\x64;C:\Users\notoraptor\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\WinSDK\Bin;C:\Users\notoraptor\data\programs\Anaconda3\envs\python2;C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\Library\mingw-w64\bin;C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\Library\usr\bin;C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\Library\bin;C:\Users\notoraptor\data\programs\Anaconda3\envs\python2\Scripts;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\WinMerge;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\notoraptor\AppData\Local\Microsoft\WindowsApps;C:\Users\notoraptor\data\programs\bin;C:\Program Files (x86)\Notepad++;C:\Program Files\NVIDIA Corporation\NVSMI;
```
So, I compile with following command:
```
(python2) C:\Users\notoraptor\mila\dev\git\theano>g++ test_gpuarray.cpp -o test_gpuarray -lgpuarray
```
And here is the output of program:
```
(python2) C:\Users\notoraptor\mila\dev\git\theano>test_gpuarray
Context initialized.
Device name: GeForce GTX 1050
Unique ID: 0000:01:00.0
Blasted.
Freeing tmp.
Freeing context.
[cuda blas teardown]
end.
```
NB: To check if code really go into culprint function (`teardown()` in `gpuarray_blas_cuda_cublas.c`), I added a small fprintf into that function body:
```
notoraptor@DESKTOP-HVUEVJI MINGW64 ~/mila/dev/git/libgpuarray (master)
$ git diff
```
```patch
diff --git a/src/gpuarray_blas_cuda_cublas.c b/src/gpuarray_blas_cuda_cublas.c
index ba4ac2b37..a63857243 100644
--- a/src/gpuarray_blas_cuda_cublas.c
+++ b/src/gpuarray_blas_cuda_cublas.c
@@ -314,6 +314,8 @@ static void teardown(gpucontext *c) {
   if (ctx->blas_handle == NULL)
     return;

+  fprintf(stderr, "[cuda blas teardown]\n");
+
   cuda_enter(ctx);
   cublasDestroy(handle->h);
   GpuKernel_clear(&handle->sgemvBH_N_a1_b1_small);
```

```
(python2) C:\Users\notoraptor\mila\dev\git\theano>python -c "import pygpu; print(pygpu.__version__)"
0.7.4+2.g671022089.dirty
```

As said, Python equivalent code (in previous comment) still fails:
```
(python2) C:\Users\notoraptor\mila\dev\git>python tmp.py cuda
Pygpu version: 0.7.4+2.g671022089.dirty
Device: GeForce GTX 1050
Unique ID: 0000:01:00.0
tmp
ctx
[cuda blas teardown]

(python2) C:\Users\notoraptor\mila\dev\git>
```

@abergeron @nouiz

**Comment by notoraptor** [comment]
Can it be related to something about threading in Python ? (python thead vs cuda or cublas thread) ?

**Comment by lamblin** [comment]
Not sure if it is related, but could it be that a compiled binary, either in libgpuarray or in the theano cache, gets loaded with the wrong libpython? I remember something similar having happened when the libpython supplied by tortoiseGit (or some similar software) was picked up instead of the one I was using.

**Comment by notoraptor** [comment]
Well, I uninstalled Anaconda, then reinstalled it with its latest version (anaconda 5.0), recreated an environment (python2) with local-compiled version of libgpuarray/pygpu, and now everything works!
```
(python2) C:\Users\notoraptor\mila\dev\git>python tmp.py cuda
Pygpu version: 0.7.4+2.g671022089
Device: GeForce GTX 1050
Unique ID: 0000:01:00.0
tmp
ctx
end

(python2) C:\Users\notoraptor\mila\dev\git>
```
(and pygpu is even loaded faster).

So, maybe the problem was related to some packages, I will never know.

I guess this ticket can be closed.

@lamblin @nouiz @abergeron
